import type { ProfileWithHiddenWorlds, MarketListing, Match, HiddenWorld, MarketInterest } from '@/types';

const hw = (id: string, profileId: string, name: Record<string, string>, category: string, order: number): HiddenWorld => ({
  id, profile_id: profileId, name, category, visibility: 'members', sort_order: order, created_at: '2025-01-01',
});

export const SEED_PROFILES: ProfileWithHiddenWorlds[] = [
  {
    id: 'p1', user_id: 'u1', full_name: 'Mariana Voss', native_name: null, initials: 'MV',
    class_name: 'Class 26', headline: { en: 'Climate-tech VC' }, role: { en: 'Partner, Green Horizon Ventures' },
    intro: { en: 'I look at the overlap of climate science and capital markets. Previously led sustainable finance at ING and advised the EU taxonomy team.' },
    professional: { en: 'Climate finance, ESG frameworks, venture investing in hard-tech decarbonization.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'whatsapp', contact_value: '+31 6 1234 5678',
    is_active: true, is_featured: true, is_curator: false, founder_no: 1,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw1', 'p1', { en: 'Fermenting hot sauces' }, 'craft', 0),
      hw('hw2', 'p1', { en: 'Nocturnal birdwatching' }, 'nature', 1),
      hw('hw3', 'p1', { en: 'Stoic philosophy reading group' }, 'mind', 2),
    ],
    ask_topics: [{ en: 'Carbon credit market structure' }, { en: 'LP relations' }],
    want_topics: [{ en: 'Intro to biochar founders' }, { en: 'Co-writing a climate brief' }],
    languages: ['English', 'Dutch', 'German'],
  },
  {
    id: 'p2', user_id: 'u2', full_name: '陈思远', native_name: 'Siyuan Chen', initials: 'SC',
    class_name: 'Class 26', headline: { en: 'Serial edtech founder', zh: '连续教育科技创业者' },
    role: { en: 'CEO, LearnBridge', zh: 'LearnBridge CEO' },
    intro: { en: 'Built two ed-tech companies in Southeast Asia. Obsessed with how people actually learn versus how we think they learn.' },
    professional: { en: 'Edtech, product-led growth, SEA market entry.' },
    bio: null, avatar_url: null, preferred_language: 'zh',
    contact_kind: 'wechat', contact_value: 'siyuan_chen88',
    is_active: true, is_featured: false, is_curator: false, founder_no: 2,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw4', 'p2', { en: 'Competitive mahjong', zh: '竞技麻将' }, 'mind', 0),
      hw('hw5', 'p2', { en: 'Vintage synthesizer collecting', zh: '复古合成器收藏' }, 'art', 1),
    ],
    ask_topics: [{ en: 'SEA market entry' }, { en: 'Product metrics for learning' }],
    want_topics: [{ en: 'Mandarin tutoring exchange' }, { en: 'Music jam session partners' }],
    languages: ['中文', 'English'],
  },
  {
    id: 'p3', user_id: 'u3', full_name: 'Alejandra Ruiz', native_name: null, initials: 'AR',
    class_name: 'Class 27', headline: { en: 'Impact lawyer turned founder' },
    role: { en: 'Founder, Derecho Digital' },
    intro: { en: 'Spent a decade in human-rights law in Latin America. Now building tech to make legal aid accessible.' },
    professional: { en: 'Legal tech, access to justice, social enterprise.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'whatsapp', contact_value: '+52 55 1234 5678',
    is_active: true, is_featured: true, is_curator: false, founder_no: 3,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw6', 'p3', { en: 'Mezcal distillation' }, 'craft', 0),
      hw('hw7', 'p3', { en: 'Pre-Columbian archaeology' }, 'mind', 1),
      hw('hw8', 'p3', { en: 'Ultra-trail running' }, 'nature', 2),
    ],
    ask_topics: [{ en: 'Legal-tech product design' }, { en: 'Fundraising in LATAM' }],
    want_topics: [{ en: 'Running partner in the Alps' }, { en: 'Mezcal tasting exchange' }],
    languages: ['Español', 'English', 'Portuguese'],
  },
  {
    id: 'p4', user_id: 'u4', full_name: 'พิชญ์ สุขสวัสดิ์', native_name: 'Pich Suksawat', initials: 'PS',
    class_name: 'Class 26', headline: { en: 'Supply-chain architect', th: 'สถาปนิกซัพพลายเชน' },
    role: { en: 'VP Operations, NovaTrade' },
    intro: { en: 'I redesign supply chains to be both leaner and more resilient. Previously with DHL and McKinsey in Bangkok.' },
    professional: { en: 'Supply chain, logistics optimization, Thailand market.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'email', contact_value: 'pich@novatrade.co',
    is_active: true, is_featured: false, is_curator: false, founder_no: 4,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw9', 'p4', { en: 'Thai boxing coaching' }, 'nature', 0),
      hw('hw10', 'p4', { en: 'Mechanical watch repair' }, 'craft', 1),
    ],
    ask_topics: [{ en: 'Last-mile logistics' }, { en: 'Cold chain tech' }],
    want_topics: [{ en: 'Watch restoration workshop' }, { en: 'Sparring partner' }],
    languages: ['ไทย', 'English'],
  },
  {
    id: 'p5', user_id: 'u5', full_name: '김지수', native_name: 'Jisoo Kim', initials: 'JK',
    class_name: 'Class 27', headline: { en: 'Fintech product lead', ko: '핀테크 프로덕트 리드' },
    role: { en: 'Head of Product, PayBridge Korea' },
    intro: { en: 'Building cross-border payment rails for SMBs. Previously at Toss and Samsung Pay.' },
    professional: { en: 'Payments, mobile UX, Korean fintech.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'email', contact_value: 'jisoo@paybridge.kr',
    is_active: true, is_featured: false, is_curator: false, founder_no: 5,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw11', 'p5', { en: 'Ceramics & pottery' }, 'art', 0),
      hw('hw12', 'p5', { en: 'Korean temple food' }, 'craft', 1),
      hw('hw13', 'p5', { en: 'Zen meditation' }, 'mind', 2),
    ],
    ask_topics: [{ en: 'Cross-border payments' }, { en: 'Mobile UX best practices' }],
    want_topics: [{ en: 'Pottery studio sharing' }, { en: 'Temple food cooking class' }],
    languages: ['한국어', 'English'],
  },
  {
    id: 'p6', user_id: 'u6', full_name: 'Oliver Blackwood', native_name: null, initials: 'OB',
    class_name: 'Class 26', headline: { en: 'Biotech operator' },
    role: { en: 'COO, Meridian Therapeutics' },
    intro: { en: 'Scaling biotech from bench to market. Background in pharma ops at Roche and a brief stint in the NHS.' },
    professional: { en: 'Biotech operations, clinical trials, regulatory strategy.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'email', contact_value: 'oliver@meridiantx.com',
    is_active: true, is_featured: false, is_curator: true, founder_no: 6,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw14', 'p6', { en: 'Amateur astronomy' }, 'nature', 0),
      hw('hw15', 'p6', { en: 'Blues harmonica' }, 'art', 1),
    ],
    ask_topics: [{ en: 'Biotech fundraising' }, { en: 'Regulatory pathways' }],
    want_topics: [{ en: 'Stargazing trips' }, { en: 'Jam session buddies' }],
    languages: ['English'],
  },
  {
    id: 'p7', user_id: 'u7', full_name: 'Fatima Al-Rashid', native_name: null, initials: 'FA',
    class_name: 'Class 27', headline: { en: 'Circular economy strategist' },
    role: { en: 'Director, Loop Materials' },
    intro: { en: 'Working on closing the loop in fashion and packaging. Based in Dubai, previously with IKEA sustainability team.' },
    professional: { en: 'Circular economy, sustainable materials, fashion supply chain.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'whatsapp', contact_value: '+971 50 123 4567',
    is_active: true, is_featured: true, is_curator: false, founder_no: 7,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw16', 'p7', { en: 'Arabic calligraphy' }, 'art', 0),
      hw('hw17', 'p7', { en: 'Desert falconry' }, 'nature', 1),
      hw('hw18', 'p7', { en: 'Angel investing in women-led startups' }, 'money', 2),
    ],
    ask_topics: [{ en: 'Sustainable packaging' }, { en: 'Fashion circularity' }],
    want_topics: [{ en: 'Calligraphy workshop host' }, { en: 'Women founders to back' }],
    languages: ['English', 'Arabic'],
  },
  {
    id: 'p8', user_id: 'u8', full_name: 'Henrik Lindqvist', native_name: null, initials: 'HL',
    class_name: 'Class 26', headline: { en: 'Proptech founder' },
    role: { en: 'CEO, Stacked Living' },
    intro: { en: 'Building modular housing solutions for the Nordics. Previously in real-estate finance at Akelius.' },
    professional: { en: 'Proptech, modular construction, Nordic real estate.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'email', contact_value: 'henrik@stackedliving.se',
    is_active: true, is_featured: false, is_curator: false, founder_no: 8,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw19', 'p8', { en: 'Sourdough baking' }, 'craft', 0),
      hw('hw20', 'p8', { en: 'Cross-country skiing' }, 'nature', 1),
    ],
    ask_topics: [{ en: 'Modular construction' }, { en: 'Proptech fundraising' }],
    want_topics: [{ en: 'Sourdough starter exchange' }, { en: 'Ski trip planning' }],
    languages: ['English', 'Swedish'],
  },
  {
    id: 'p9', user_id: 'u9', full_name: 'Priya Nair', native_name: null, initials: 'PN',
    class_name: 'Class 27', headline: { en: 'Health-tech product designer' },
    role: { en: 'Design Lead, CareStack' },
    intro: { en: 'Designing digital health experiences. Background in UX at Philips Health and a Masters in biomedical engineering.' },
    professional: { en: 'Health-tech UX, digital therapeutics, medical device design.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'whatsapp', contact_value: '+91 98765 43210',
    is_active: true, is_featured: false, is_curator: false, founder_no: 9,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw21', 'p9', { en: 'Bharatanatyam dance' }, 'art', 0),
      hw('hw22', 'p9', { en: 'Quantum computing study group' }, 'build', 1),
    ],
    ask_topics: [{ en: 'Health-tech UX' }, { en: 'Regulatory in digital health' }],
    want_topics: [{ en: 'Dance class exchange' }, { en: 'Quantum computing reading group' }],
    languages: ['English', 'Hindi', 'Tamil'],
  },
  {
    id: 'p10', user_id: 'u10', full_name: 'Tomás Ferreira', native_name: null, initials: 'TF',
    class_name: 'Class 26', headline: { en: 'Agri-fintech builder' },
    role: { en: 'CTO, TerraPay Brasil' },
    intro: { en: 'Building payment and credit infrastructure for smallholder farmers in Brazil.' },
    professional: { en: 'Agritech, financial inclusion, Brazil market.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'whatsapp', contact_value: '+55 11 99876 5432',
    is_active: true, is_featured: false, is_curator: false, founder_no: 10,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw23', 'p10', { en: 'Capoeira' }, 'nature', 0),
      hw('hw24', 'p10', { en: 'Street photography' }, 'art', 1),
      hw('hw25', 'p10', { en: 'Coffee roasting' }, 'craft', 2),
    ],
    ask_topics: [{ en: 'Financial inclusion' }, { en: 'Agri supply chain' }],
    want_topics: [{ en: 'Photo walk partners' }, { en: 'Coffee cupping session' }],
    languages: ['English', 'Portuguese'],
  },
  {
    id: 'p11', user_id: 'u11', full_name: 'Yuki Tanaka', native_name: '田中ゆき', initials: 'YT',
    class_name: 'Class 27', headline: { en: 'Deep-tech investor' },
    role: { en: 'Principal, Kyoto Ventures' },
    intro: { en: 'Investing in robotics and advanced materials out of Japan. Former mechanical engineer at Toyota.' },
    professional: { en: 'Deep-tech VC, robotics, advanced manufacturing.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'email', contact_value: 'yuki@kyotovc.jp',
    is_active: true, is_featured: false, is_curator: false, founder_no: 11,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw26', 'p11', { en: 'Bonsai cultivation' }, 'nature', 0),
      hw('hw27', 'p11', { en: 'Kintsugi repair' }, 'craft', 1),
    ],
    ask_topics: [{ en: 'Robotics startups' }, { en: 'Japan market entry' }],
    want_topics: [{ en: 'Bonsai workshop exchange' }, { en: 'Kintsugi class' }],
    languages: ['English', '日本語'],
  },
  {
    id: 'p12', user_id: 'u12', full_name: 'Nadia Petrova', native_name: null, initials: 'NP',
    class_name: 'Class 26', headline: { en: 'AI governance researcher' },
    role: { en: 'Fellow, Oxford Internet Institute' },
    intro: { en: 'Researching AI policy and algorithmic accountability. Advising three governments on AI regulation.' },
    professional: { en: 'AI governance, tech policy, algorithmic auditing.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'email', contact_value: 'nadia@oii.ox.ac.uk',
    is_active: true, is_featured: false, is_curator: false, founder_no: 12,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw28', 'p12', { en: 'Soviet cinema restoration' }, 'art', 0),
      hw('hw29', 'p12', { en: 'Beekeeping' }, 'nature', 1),
      hw('hw30', 'p12', { en: 'Chess (2100 Elo)' }, 'mind', 2),
    ],
    ask_topics: [{ en: 'AI regulation' }, { en: 'Algorithmic auditing methods' }],
    want_topics: [{ en: 'Chess opponent' }, { en: 'Beekeeping co-op' }],
    languages: ['English', 'Russian'],
  },
  {
    id: 'p13', user_id: 'u13', full_name: 'James Okafor', native_name: null, initials: 'JO',
    class_name: 'Class 27', headline: { en: 'Creator-economy builder' },
    role: { en: 'Founder, AfriCreate' },
    intro: { en: 'Building tools for African creators to monetize. Previously ran partnerships at YouTube EMEA.' },
    professional: { en: 'Creator economy, content platforms, Africa market.' },
    bio: null, avatar_url: null, preferred_language: 'en',
    contact_kind: 'whatsapp', contact_value: '+234 803 123 4567',
    is_active: true, is_featured: false, is_curator: false, founder_no: 13,
    created_at: '2025-01-01', updated_at: '2025-01-01',
    hidden_worlds: [
      hw('hw31', 'p13', { en: 'Afrobeat drumming' }, 'art', 0),
      hw('hw32', 'p13', { en: 'Urban farming' }, 'nature', 1),
    ],
    ask_topics: [{ en: 'Creator monetization' }, { en: 'Africa go-to-market' }],
    want_topics: [{ en: 'Drum circle partners' }, { en: 'Rooftop garden tips' }],
    languages: ['English', 'Yoruba'],
  },
];

export const SEED_LISTINGS: (MarketListing & { creator?: ProfileWithHiddenWorlds; interests_count?: number; suggested_profile?: ProfileWithHiddenWorlds; suggested_reason?: string })[] = [
  {
    id: 'l1', creator_profile_id: 'p1', type: 'wanted',
    title: { en: 'Looking for a biochar co-pilot' },
    description: { en: 'I’m exploring a biochar startup in the Nordics. Need someone who knows carbon markets or soil science. Happy to share deal flow.' },
    tags: ['climate', 'biochar', 'co-founder'],
    chips: [{ en: 'Climate' }, { en: 'Co-founder' }],
    capacity: 1, status: 'open',
    created_at: '2025-06-10', updated_at: '2025-06-10',
    creator: SEED_PROFILES[0], interests_count: 2,
  },
  {
    id: 'l2', creator_profile_id: 'p3', type: 'wanted',
    title: { en: 'Pro-bono legal clinic for founders' },
    description: { en: 'Planning a monthly legal-aid session for founders in the cohort. Looking for 2-3 classmates who can help run it.' },
    tags: ['legal', 'pro-bono', 'clinic'],
    chips: [{ en: 'Legal' }, { en: 'Pro-bono' }],
    capacity: 3, status: 'open',
    created_at: '2025-06-12', updated_at: '2025-06-12',
    creator: SEED_PROFILES[2], interests_count: 1,
    suggested_profile: SEED_PROFILES[11],
    suggested_reason: 'Nadia advises governments on regulation — she might bring an interesting policy lens.',
  },
  {
    id: 'l3', creator_profile_id: 'p5', type: 'wanted',
    title: { en: 'Cross-border payments study group' },
    description: { en: 'Anyone interested in a bi-weekly deep-dive into cross-border payment infrastructure? I’ll share learnings from PayBridge.' },
    tags: ['fintech', 'payments', 'study-group'],
    chips: [{ en: 'Fintech' }, { en: 'Study group' }],
    capacity: 6, status: 'open',
    created_at: '2025-06-15', updated_at: '2025-06-15',
    creator: SEED_PROFILES[4], interests_count: 0,
  },
  {
    id: 'l4', creator_profile_id: 'p7', type: 'offer',
    title: { en: 'Arabic calligraphy workshop' },
    description: { en: 'I’ve been practicing for 12 years. Happy to run a 2-hour intro session for anyone curious.' },
    tags: ['calligraphy', 'arabic', 'workshop'],
    chips: [{ en: 'Art' }, { en: 'Workshop' }],
    capacity: 8, status: 'open',
    created_at: '2025-06-18', updated_at: '2025-06-18',
    creator: SEED_PROFILES[6], interests_count: 4,
  },
  {
    id: 'l5', creator_profile_id: 'p10', type: 'offer',
    title: { en: 'Coffee cupping & roasting walkthrough' },
    description: { en: 'I roast my own beans (Brazilian single-origin). Will bring gear and walk you through the process.' },
    tags: ['coffee', 'craft', 'tasting'],
    chips: [{ en: 'Craft' }, { en: 'Tasting' }],
    capacity: 5, status: 'open',
    created_at: '2025-06-20', updated_at: '2025-06-20',
    creator: SEED_PROFILES[9], interests_count: 3,
  },
  {
    id: 'l6', creator_profile_id: 'p6', type: 'offer',
    title: { en: 'Biotech regulatory office hours' },
    description: { en: 'I’ve navigated FDA, EMA, and NHS pathways. 30-min slots for anyone hitting regulatory walls.' },
    tags: ['biotech', 'regulatory', 'mentoring'],
    chips: [{ en: 'Biotech' }, { en: 'Mentoring' }],
    capacity: null, status: 'open',
    created_at: '2025-06-22', updated_at: '2025-06-22',
    creator: SEED_PROFILES[5], interests_count: 2,
  },
];

export const SEED_INTERESTS: MarketInterest[] = [
  { id: 'i1', listing_id: 'l1', profile_id: 'p8', message: { en: 'I know the Nordic carbon-offset space well.' }, status: 'pending', created_at: '2025-06-11' },
  { id: 'i2', listing_id: 'l1', profile_id: 'p6', message: { en: 'I have biotech experience that might cross-pollinate.' }, status: 'pending', created_at: '2025-06-12' },
  { id: 'i3', listing_id: 'l4', profile_id: 'p5', message: { en: 'I love calligraphy — would love to join!' }, status: 'accepted', created_at: '2025-06-19' },
];

export const SEED_MATCHES: (Match & { listing?: MarketListing; initiator?: ProfileWithHiddenWorlds; matched?: ProfileWithHiddenWorlds })[] = [
  {
    id: 'm1', listing_id: 'l4', initiator_profile_id: 'p5', matched_profile_id: 'p7',
    status: 'connected', source: 'self',
    next_step: { en: 'Meet at the calligraphy workshop, Saturday 2pm' },
    created_at: '2025-06-20', completed_at: null,
    listing: SEED_LISTINGS[3],
    initiator: SEED_PROFILES[4],
    matched: SEED_PROFILES[6],
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  craft: '#8f7044',
  nature: '#465a49',
  mind: '#405069',
  build: '#5a4a6a',
  money: '#6f552f',
  art: '#8a3a32',
};

export const CATEGORY_ICONS: Record<string, string> = {
  craft: 'star',
  nature: 'globe',
  mind: 'bookmark',
  build: 'link',
  money: 'landmark',
  art: 'quote',
};
